version: "3.7"
services:
  jenkins:
    build:
      context: ./
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    restart: "always"